// Node types: "person", "organization", "location"
const graphData = {
    nodes: [
        // CENTER
        {id:"epstein",label:"Jeffrey Epstein",type:"center",radius:36,
            agency:"CENTRAL NODE",role:"Financier · Sex Trafficker · Convicted",status:"CONVICTED",networth:"$577M (at death)",
            intelRole:"Convicted sex offender and suspected intelligence asset. Died in federal custody 2019.",
            epsteinLink:"Every connection here documented through visits, emails, payments, or court filings.",
            significance:"His network of the world's most powerful men remains only partially prosecuted.",
            desc:"Jeffrey Epstein was a financier and convicted sex offender who ran a multi-decade trafficking operation targeting young women and minors. He cultivated heads of state, royalty, billionaires, and celebrities — offering access and capital in exchange for participation in a network designed to generate compromising material and blackmail leverage.",
            evidence:"Convicted 2008 in Florida on a secret non-prosecution deal. Re-arrested July 2019 on federal sex trafficking charges. Found dead August 10, 2019 in MCC New York — ruled suicide, disputed by independent pathologist Dr. Michael Baden who found evidence consistent with homicidal strangulation. Properties contained hidden cameras in bedrooms. His contact book listed over 1,000 names.",
            link:"Epstein is the center. Every other node connects through documented visits, financial ties, court testimony, victim allegations, or his own emails. Maxwell is the only person convicted despite Giuffre and others naming dozens of men under oath."},

        // CONVICTED
        {id:"maxwell_g",label:"Ghislaine Maxwell",type:"convicted",radius:30,
            agency:"CO-CONSPIRATOR — CONVICTED 2021",role:"Socialite · Recruiter · Trafficker",status:"CONVICTED",networth:"$20M (pre-arrest)",
            intelRole:"Epstein's partner and primary recruiter. Daughter of confirmed Mossad asset Robert Maxwell.",
            epsteinLink:"Recruited and groomed victims for decades. Managed household, travel, and client access.",
            significance:"20-year sentence. Refuses to name other participants. Protecting someone.",
            desc:"Ghislaine Maxwell was Epstein's long-term companion, fixer, and primary recruiter. She managed his properties, recruited girls as young as 14, and according to multiple victims, participated directly in abuse. She entered Epstein's world in 1991 immediately after her father Robert Maxwell — a confirmed Mossad asset — died under disputed circumstances.",
            evidence:"Convicted December 2021 on five counts including sex trafficking of a minor. Sentenced June 2022 to 20 years. Multiple victims testified she directly participated in grooming and abuse. She has refused to cooperate with prosecutors in identifying other participants throughout her sentence.",
            link:"Her silence — maintained through a 20-year federal sentence — is the central unanswered question of the case. Legal analysts widely believe she is protecting specific individuals."},

        {id:"brunel",label:"Jean-Luc Brunel",type:"convicted",radius:20,
            agency:"MC2 MODEL MANAGEMENT",role:"Modeling Mogul · European Recruiter",status:"DIED BEFORE TRIAL",networth:"$50M (estimated)",
            intelRole:"French modeling impresario. Used his agencies as a direct European victim pipeline for Epstein.",
            epsteinLink:"Received $1M from Epstein to found MC2. Supplied girls from Eastern Europe and Brazil.",
            significance:"Found dead in Paris cell Feb 2022 — second key witness to die before testifying.",
            desc:"Jean-Luc Brunel ran MC2 Model Management, directly funded by a $1M wire from Epstein, and used his modeling industry access to recruit vulnerable young women into Epstein's network. Virginia Giuffre and multiple other victims named him as a direct participant in abuse.",
            evidence:"$1M transfer from Epstein to MC2 documented. Multiple victims named Brunel as a direct abuser. Arrested France December 2020 on rape of minors charges. Found dead in his Paris prison cell February 19, 2022 — ruled suicide.",
            link:"His death before trial — like Epstein's — eliminated testimony that would have named his client list. Two key witnesses eliminated. The pattern has never been investigated."},

        {id:"nader",label:"George Nader",type:"convicted",radius:11,
            agency:"TRUMP/UAE POLITICAL FIXER",role:"Political Operative · Convicted Pedophile",status:"CONVICTED",networth:"UNKNOWN",
            intelRole:"Back-channel between Trump transition and UAE. Twice-convicted on child abuse charges.",
            epsteinLink:"Operated in same world of wealthy political brokers using access as a shield.",
            significance:"Convicted 2020: 10 years for child pornography and child sex trafficking.",
            desc:"George Nader was a political operative who served as a key back-channel between the Trump transition team and the UAE, and a central figure in the Mueller investigation. He was simultaneously a twice-convicted pedophile.",
            evidence:"First convicted Czech Republic 1991 for sexual abuse of minors. Convicted again US 2020 on transporting child pornography and sex trafficking of a minor — sentenced to 10 years. Mueller investigation cooperating witness.",
            link:"Nader demonstrates Epstein was not an anomaly but part of a broader ecosystem in which extremely wealthy political operatives with child abuse histories operated with impunity for decades."},

        // SUSPICIOUS / NAMED IN FILES
        {id:"trump",label:"Donald Trump",type:"suspicious",radius:24,
            agency:"45TH & 47TH US PRESIDENT",role:"Businessman · President",status:"NAMED IN FILES",networth:"$5.4B",
            intelRole:"Decades-long social relationship with Epstein. Publicly praised him. Named in victim deposition.",
            epsteinLink:"Called Epstein 'terrific guy who likes beautiful women, many on the younger side.'",
            significance:"Giuffre named Trump in deposition. Epstein died under his DOJ. AG's father gave Epstein his first job.",
            desc:"Donald Trump had a documented social relationship with Epstein from the late 1980s through the early 2000s. Both men moved in the same New York and Palm Beach elite circles. The circumstances of Epstein's 2019 death — under Trump's DOJ, run by Bill Barr whose OSS-officer father gave Epstein his career start at Dalton School — have never been formally examined.",
            evidence:"1992 video shows Trump and Epstein at Mar-a-Lago with cheerleaders. Trump said in 2002: 'I've known Jeff for fifteen years. Terrific guy. It is even said that he likes beautiful women as much as I do, and many of them are on the younger side.' Virginia Giuffre's deposition named Trump. Epstein held a Mar-a-Lago membership. AG Bill Barr, whose father Donald Barr (OSS officer) gave Epstein his career start at Dalton, oversaw DOJ during Epstein's arrest and death.",
            link:"The highest-profile living name in the files. His praise of Epstein, Giuffre's deposition, and Epstein dying under his administration — run by the son of the man who launched Epstein's career — form a pattern no investigation has ever examined."},

        {id:"clinton",label:"Bill Clinton",type:"suspicious",radius:22,
            birthday_book: true,
            agency:"42ND US PRESIDENT",role:"Former President",status:"NAMED IN FILES",networth:"$120M",
            intelRole:"Bill Clinton appears on pilot David Rodgers' flight logs for Epstein's Boeing 727 at least 26 times. On at least some flights, Secret Service personnel are not listed on the manifest — though the full circumstances of their presence or absence have not been independently verified beyond the logs themselves. Virginia Giuffre stated in court filings that Clinton visited Epstein's island. Clinton has denied visiting the island. No law enforcement agency has publicly confirmed an investigation into Clinton's relationship with Epstein.",
            epsteinLink:"Flight logs maintained by pilot David Rodgers document at least 26 Clinton flights on Epstein's aircraft, including international trips to Africa and Europe. Some trips were associated with Clinton Foundation initiatives. Clinton aide Doug Band appears in communications related to scheduling with Epstein's office. Clinton attended events at Epstein's Manhattan residence. Epstein made donations to the Clinton Foundation. Giuffre's court filings state Clinton was present on Epstein's island — a claim Clinton's office has denied. Clinton's office has stated he knew nothing about Epstein's crimes. Clinton has not been charged with any crime related to Epstein. No public record indicates he has been questioned by law enforcement about the relationship.",
            desc:"William Jefferson Clinton (b. 1946), 42nd President of the United States. After leaving office, he flew on Epstein's aircraft at least 26 times according to pilot flight logs — among the highest documented totals for any public figure. Some flights were connected to Clinton Foundation activities. His aide Doug Band coordinated scheduling with Epstein's office. Clinton attended events at Epstein's Manhattan townhouse. Epstein donated to the Clinton Foundation. Giuffre placed Clinton on Epstein's island in court filings — Clinton's office has denied this. Clinton has not been charged, investigated, or publicly questioned by law enforcement regarding his relationship with Epstein.",
            evidence:"Pilot David Rodgers' flight logs: 26+ Clinton flights on Epstein's aircraft. Some flights lack Secret Service personnel on manifest — full circumstances unverified. Giuffre's court filings place Clinton on Little St. James — denied by Clinton's office. Epstein's contact book contains multiple Clinton-related entries. Doug Band communications with Epstein's office documented in released materials. Clinton attended events at Epstein's Manhattan residence. Epstein donated to the Clinton Foundation. No criminal charges. No public investigation. No known law enforcement questioning.",
            significance:"The volume of Clinton's documented travel on Epstein's aircraft — 26+ flights — is among the highest of any political figure in the released records. Despite this, no law enforcement agency has publicly investigated or questioned him about the relationship. The gap between the volume of documented contact and the absence of any formal inquiry remains one of the most noted aspects of the Epstein case.",
            link:"Twenty-six documented flights on Epstein's aircraft. Events at the Manhattan residence. Foundation donations from Epstein. A victim who places him on the island — which he denies. No charges. No public investigation. No known questioning by law enforcement. The volume of documented contact and the absence of formal inquiry remain unreconciled."},
            
        {id:"andrew",label:"Prince Andrew",type:"suspicious",radius:21,
            agency:"DUKE OF YORK — UK ROYAL",role:"British Royal · Former Trade Envoy",status:"SETTLED SUIT",networth:"$35M",
            intelRole:"Long documented friendship with Maxwell and Epstein. Photographed with Giuffre aged 17.",
            epsteinLink:"Stayed at multiple Epstein properties. Photograph places him with 17-year-old Giuffre.",
            significance:"Settled Giuffre civil suit for ~£12M in 2022. Stripped of all royal duties.",
            desc:"Prince Andrew's relationship with Maxwell and Epstein was extensive and long-documented. A photograph showing Andrew with his arm around Virginia Giuffre — then 17, who alleges she was trafficked to him — became the defining image of royal involvement in the scandal.",
            evidence:"Photograph with Giuffre and Maxwell at Maxwell's London home 2001, when Giuffre was 17. Andrew denied authenticity, claimed he couldn't sweat, gave a catastrophic BBC Newsnight interview in 2019. Settled Giuffre's US civil suit February 2022 for a reported ~£12M without admitting liability. Stripped of military titles and patronages.",
            link:"Paying eight figures to avoid civil trial is the strongest implicit acknowledgment of legal exposure outside Maxwell's conviction. The settlement prevents Giuffre from testifying against him in any future proceeding."},

        {id:"musk",label:"Elon Musk",type:"suspicious",radius:18,
            agency:"TESLA / SPACEX / X / US DOGE",role:"Billionaire · Presidential Adviser · X Platform Owner",status:"NAMED IN FILES — SUBPOENAED BY USVI",networth:"$338B",
            intelRole:"The richest person in the world, senior adviser to the US President, and owner of the platform that experienced a historic surge in child sexual abuse material after he gutted its safety infrastructure. His team actively sought an invitation to Epstein's private island. He emailed Epstein on Christmas Day. His brother Kimbal Musk dated one of Epstein's associates. He was subpoenaed by the US Virgin Islands in their investigation into Epstein's network. His public claim of minimal contact is contradicted at every turn by the documentary record.",
            epsteinLink:"Musk's connection to Epstein was not incidental — it was actively pursued from his side. A Musk assistant contacted Epstein's office explicitly requesting an invitation to Little St. James island for Elon. Musk personally emailed Epstein on Christmas Day — not a date associated with casual professional correspondence. Separate correspondence shows Musk asking Epstein to facilitate introductions to academics and scientists, using Epstein as a social broker in exactly the way Epstein designed his network to function. Musk's brother Kimbal Musk reportedly dated a woman connected to Epstein's circle. In 2023, the US Virgin Islands issued a subpoena to Elon Musk as part of their civil enforcement action against JPMorgan over the bank's facilitation of Epstein's sex trafficking operation — indicating prosecutors believed Musk possessed information material to the investigation. Musk has publicly claimed his contact with Epstein was limited to a single brief meeting at someone else's event, a claim the documentary record demolishes. The assistant's island invitation request alone proves advance planning and deliberate pursuit of access to Epstein's most private and incriminating location — the island where victims were trafficked and where hidden cameras recorded compromising material on visitors.",
            desc:"Elon Musk (b. 1971) is the CEO of Tesla, SpaceX, and owner of the social media platform X (formerly Twitter), which he acquired in October 2022. He serves as a senior adviser to President Trump through his role leading the Department of Government Efficiency (DOGE). He is the richest person in the world. Musk appears in the released Epstein files through multiple documented points of contact that reveal active pursuit of Epstein's network from Musk's side. His assistant explicitly requested an island invitation. Musk emailed Epstein on Christmas Day. He sought academic introductions through Epstein. His brother Kimbal Musk had social connections to Epstein's circle. The US Virgin Islands subpoenaed Musk in their investigation. After acquiring Twitter/X in October 2022, Musk fired approximately 80% of the company's staff, including the vast majority of its trust and safety team — the division responsible for detecting and removing child sexual abuse material (CSAM). The consequences were immediate and catastrophic. The National Center for Missing & Exploited Children (NCMEC) reported that reports of CSAM on the platform surged dramatically. The Stanford Internet Observatory documented a significant increase in CSAM and child exploitation content. The EU's Digital Services Act coordinator flagged X for systemic failures in content moderation. Researchers found that known CSAM accounts that had been previously suspended were able to return and operate openly. Musk's gutting of child safety infrastructure at the world's largest real-time communication platform — while simultaneously appearing in the files of history's most prominent child sex trafficker — represents a convergence that no public body has examined. The man in Epstein's files dismantled the system designed to protect children online, and he did it while serving as a senior adviser to the President of the United States.",
            evidence:"Released DOJ files include an email from a Musk assistant explicitly requesting an invitation to Little St. James island — Epstein's private Caribbean property where victims were trafficked and hidden cameras recorded visitors. A Christmas Day email from Musk to Epstein is documented — the kind of personal correspondence that contradicts claims of minimal contact. Separate correspondence shows Musk asking Epstein to facilitate academic introductions, using Epstein as a social broker. Kimbal Musk, Elon's brother, reportedly had social ties to a woman in Epstein's circle. The US Virgin Islands issued a subpoena to Elon Musk in 2023 as part of their civil enforcement action investigating JPMorgan's role in facilitating Epstein's trafficking — the subpoena indicates prosecutors believed Musk had material information. After acquiring Twitter/X in October 2022, Musk fired the majority of the trust and safety team including head of trust and safety Yoel Roth. NCMEC reported a surge in CSAM reports on the platform. The Stanford Internet Observatory documented increased child exploitation content. The EU Digital Services Act coordinator cited X for systemic moderation failures. The Ghost Data research group found that previously banned CSAM accounts were able to return and operate. Multiple child safety organizations issued public warnings about the platform's deterioration. Musk publicly claimed his Epstein contact was limited to one incidental meeting — a claim contradicted by multiple documented correspondence points, the assistant's island invitation request, and the USVI subpoena.",
            significance:"Elon Musk is the richest person in the world, a senior adviser to the US President with access to classified government systems through DOGE, the owner of one of the world's largest communication platforms, and the head of companies with the most sensitive US government contracts (SpaceX launches classified military and intelligence satellites, Starlink provides battlefield communications). He appears in a convicted sex trafficker's files through documented active pursuit of access to that trafficker's private island. He was subpoenaed by prosecutors investigating the trafficking operation. His brother had connections to the trafficker's circle. And after all of this became public, he gutted the child safety infrastructure at the platform he controls — creating the largest surge in child sexual abuse material on a major social media platform in history. The combination of his appearance in Epstein's files, the USVI subpoena, the Kimbal connection, and the deliberate dismantling of child safety systems has never been examined by any body with investigative authority. He currently has more access to US government systems than perhaps any private citizen in history.",
            link:"The richest man in the world actively sought an invitation to a sex trafficker's private island, emailed that trafficker on Christmas Day, was subpoenaed by prosecutors investigating the trafficking operation, and then — after acquiring the world's largest real-time communication platform — fired the teams responsible for protecting children from sexual exploitation, producing a historic surge in CSAM. His brother had ties to Epstein's circle. He now advises the President and has access to the most sensitive government systems in existence. No investigation has examined any of it. The question is not what Musk knew — it's what leverage exists over a man with this much power who pursued access to a sexual blackmail operation."},
        {id:"gates",label:"Bill Gates",type:"suspicious",radius:17,
            agency:"MICROSOFT / GATES FOUNDATION",role:"Billionaire Philanthropist",status:"NAMED IN FILES",networth:"$134B",
            intelRole:"Met Epstein multiple times post-conviction. Foundation staff maintained extensive contact.",
            epsteinLink:"Met Epstein at least 3 times after 2008. Considered letting Epstein manage a charitable fund.",
            significance:"Melinda warned him. Divorce cited Epstein. Foundation adviser named in Epstein's will.",
            desc:"Bill Gates maintained sustained documented contact with Epstein years after his 2008 sex offender conviction. The relationship extended to plans for Epstein to manage a Gates charitable fund, significant enough that Epstein named a Gates Foundation adviser as backup executor of his will without that person's knowledge.",
            evidence:"Multiple meetings at Epstein's Manhattan townhouse documented 2011-2013. Gates Foundation chief scientific adviser Boris Nikolic named without his consent as backup executor of Epstein's will. Melinda Gates explicitly warned her husband. The Epstein connection was cited in the Gates divorce proceedings.",
            link:"Gates met a convicted sex offender repeatedly, was warned by his wife, and considered giving Epstein control of a charitable fund. What Epstein offered or held over Gates has never been disclosed."},

            
        {id:"staley",label:"Jes Staley",type:"suspicious",radius:28,
            most_suspicious: true,
            agency:"JPMORGAN CHASE / BARCLAYS",role:"Banker · CEO · Epstein's Financial Infrastructure",status:"RESIGNED IN DISGRACE — FINED — BANNED",networth:"$120M",
            intelRole:"Jes Staley is the reason Epstein's operation had money. As head of JPMorgan's Private Bank, he maintained Epstein's accounts for over a decade — through an indictment, a conviction, and a sex offender registration. JPMorgan's own compliance officers flagged the accounts repeatedly: large cash withdrawals, wire transfers to young women, transaction patterns consistent with sex trafficking. Every flag was overridden. Staley had the authority to override them. When he left JPMorgan in 2013, the bank closed Epstein's accounts almost immediately. The accounts did not survive his departure. He was the relationship.",
            epsteinLink:"Staley ran JPMorgan's Private Bank — the division for ultra-high-net-worth clients. Epstein was his client. This wasn't arm's-length banking. He exchanged approximately 1,200 emails with Epstein. He visited the Manhattan townhouse. He visited the Palm Beach mansion. He visited Little St. James island. He visited Epstein in the Palm Beach County Stockade during his 2008 sentence — he traveled to see a convicted sex offender in jail, not to end the relationship but to maintain it. The 'snow white' email — in which Staley referenced a young woman using fairy tale language in correspondence with a convicted sex trafficker — has never been fully released. Its context remains sealed. Epstein's accounts moved hundreds of millions of dollars during the relationship. That money funded jets, islands, payments to victims, and the operational infrastructure of a trafficking network. Staley kept the pipe open.",
            desc:"James Edward Staley (b. 1957). Over 30 years at JPMorgan, rising from analyst to head of the Private Bank to CEO of the Investment Bank. His Epstein relationship spanned the early 2000s through at least 2015 — surviving every event that should have ended it. After JPMorgan, he became CEO of Barclays in 2015. When questioned by the Barclays board about Epstein, he lied. The UK Financial Conduct Authority found he was 'not candid' — regulatory language for deliberate deception. Forced to resign November 2021. Fined £1.8 million. Permanently banned from senior financial positions in the UK. In 2023, JPMorgan settled with Epstein's victims for $290 million — the largest sex trafficking settlement in US history. The US Virgin Islands settled separately for $75 million. Total cost of Staley's decisions: $365 million. Internal documents produced during litigation confirmed that compliance officers had flagged Epstein's accounts, that the flags were overridden, and that senior executives including Staley were aware of Epstein's criminal status throughout.",
            evidence:"Head of JPMorgan Private Bank during Epstein relationship — corporate records. ~1,200 emails with Epstein — revealed in 2023 litigation. Visited Manhattan townhouse, Palm Beach mansion, Little St. James island — internal records and testimony. Visited Epstein in prison — Palm Beach County Stockade visitor logs. 'Snow white' email referencing a young woman — court filings. Compliance flags on Epstein's accounts overridden — internal bank records. Accounts closed promptly after Staley's 2013 departure — bank records. JPMorgan settled victims' suit for $290M, USVI suit for $75M. FCA found Staley 'not candid' about Epstein. Resigned Barclays November 2021. Fined £1.8M. Banned from senior UK financial roles. Introduced Epstein to other JPMorgan clients. JPMorgan general counsel warned about Epstein — ignored. Never criminally charged. 1,200 emails never released.",
            significance:"Without Staley, the money doesn't move. Without the money, the operation doesn't function. Every flight, every payment to a victim, every wire transfer to a recruiter, every property with hidden cameras — all of it flowed through accounts that Jes Staley personally kept open against his own bank's compliance systems. He is not a peripheral figure. He is the financial infrastructure. JPMorgan paid $365 million because of what he enabled. He was fined, banned, and forced to resign. But he was never charged. The 1,200 emails remain sealed. And the question no one has asked him under oath — what he did at those properties, what Epstein had on him, and why he accepted career-ending risk to keep a sex trafficker's accounts open — remains the single most important unasked question in the financial side of this case.",
            link:"1,200 emails. Visited the island. Visited the townhouse. Visited the mansion. Visited him in prison. Overrode the compliance flags. Sent the 'snow white' email. When he left, the accounts closed immediately — because he was the only reason they existed. $365 million in settlements. Fined. Banned. Disgraced. Never charged. The emails are still sealed. The man who kept the money flowing has never been asked a single question under oath about what he saw, what he did, and what Epstein held over him."},

        {id:"lutnick",label:"Howard Lutnick",type:"suspicious",radius:15,
            agency:"CANTOR FITZGERALD / NEWMARK / US COMMERCE SECRETARY",role:"Wall Street CEO · Trump Commerce Secretary",status:"NAMED IN FILES",networth:"$1.5B",
            intelRole:"Howard Lutnick is the current United States Secretary of Commerce — a Cabinet-level position with authority over trade policy, economic data, the Census Bureau, NOAA, and the Bureau of Industry and Security which controls export of sensitive technologies. He was previously the chairman and CEO of Cantor Fitzgerald and chairman of Newmark Group. The 2026 DOJ release contains emails showing Lutnick and his wife accepted an invitation to visit Jeffrey Epstein's private island Little St. James in December 2012 — three and a half years after Epstein's 2008 sex offender conviction — planning to arrive by yacht with their children. Additional 2011 correspondence shows Lutnick having drinks with Epstein and discussing a nearby building project. This documented post-conviction social relationship directly contradicts Lutnick's prior public claims that he cut ties with Epstein 'decades ago.' He made those claims during the period he was being vetted for a Cabinet position in the Trump administration. The contradiction between his public statements and his own emails constitutes either a failure of the vetting process or a deliberate decision to overlook it. Lutnick was confirmed as Commerce Secretary despite the existence of these emails in DOJ files — meaning the administration either did not review the files, reviewed them and did not care, or reviewed them and determined the relationship was not disqualifying. Each possibility raises its own set of questions. A sitting Cabinet secretary with authority over sensitive technology exports and economic intelligence visited a convicted sex trafficker's private island with his family — the same island where victims were trafficked and hidden cameras recorded visitors — and currently holds one of the most sensitive positions in the US government.",
            epsteinLink:"The 2026 DOJ release contains email correspondence showing Lutnick accepting an invitation from Epstein to visit Little St. James island in December 2012. The emails indicate Lutnick planned to arrive by yacht with his wife and children. This was not an ambiguous social encounter — it was a planned multi-day visit to the private Caribbean island of a registered sex offender, arranged through direct correspondence, involving the transport of the Lutnick family to the location where Virginia Giuffre and other victims have testified they were trafficked and abused, and where hidden surveillance cameras recorded visitors in compromising situations. Separate 2011 correspondence documents Lutnick meeting Epstein for drinks and discussing a building project near Epstein's property — indicating an ongoing social and potentially business relationship years after Epstein's conviction. The December 2012 island visit means Lutnick maintained an active social relationship with Epstein for at least four years after the 2008 conviction — a period during which Epstein's sex offender status was a matter of public record and during which Epstein was required to register as a sex offender in multiple jurisdictions. Lutnick's prior public statement that he cut ties with Epstein 'decades ago' is directly and unambiguously contradicted by his own emails. The phrase 'decades ago' implies a separation occurring in the 1990s or earlier — the 2012 island visit email makes this claim false on its face.",
            desc:"Howard William Lutnick (b. 1961) is the chairman and CEO of Cantor Fitzgerald, one of Wall Street's most prominent financial services firms, and chairman of Newmark Group, a major commercial real estate company. He became widely known for his leadership of Cantor Fitzgerald after the firm lost 658 employees in the September 11 attacks — a tragedy that gave Lutnick significant public sympathy and media goodwill. In January 2025, President Trump nominated Lutnick as Secretary of Commerce. He was confirmed and currently serves in that role, with authority over the Bureau of Industry and Security (which controls technology exports and sanctions enforcement), the Census Bureau, NOAA, the Patent and Trademark Office, and economic data systems critical to national security. The 2026 DOJ file release revealed that Lutnick's relationship with Epstein extended well beyond any casual or pre-conviction social acquaintance. Emails show a December 2012 planned family visit to Epstein's private island — the most incriminating location in the entire Epstein case — and 2011 correspondence showing social meetings and business discussions. These emails directly contradict Lutnick's public claims of having severed the relationship 'decades ago.' The contradiction was not discovered by investigative journalism or congressional oversight — it was revealed by a routine DOJ document release. The fact that Lutnick was vetted for and confirmed to a Cabinet position while these emails existed in DOJ files raises fundamental questions about the integrity of the nomination process. Either the vetting failed to surface readily available DOJ documents, or the documents were surfaced and the nomination proceeded regardless.",
            evidence:"2026 DOJ release emails show Lutnick and his wife accepted an invitation to visit Epstein's Little St. James island in December 2012, planning to arrive by yacht with their children — four years after Epstein's 2008 sex offender conviction. 2011 correspondence shows Lutnick having drinks with Epstein and discussing a nearby building project. Lutnick publicly stated he cut ties with Epstein 'decades ago' — a claim directly contradicted by his own 2011 and 2012 correspondence. Lutnick was nominated and confirmed as US Commerce Secretary in 2025 despite these emails existing in DOJ files. As Commerce Secretary, Lutnick has authority over technology export controls, sanctions enforcement, economic data, and the Census Bureau. The island visit email places Lutnick at the most surveilled and compromising location in the Epstein network — a location where hidden cameras recorded visitors. No congressional inquiry has examined the contradiction between Lutnick's public statements and his documented correspondence.",
            significance:"A sitting United States Cabinet secretary visited a convicted sex trafficker's private island with his family, maintained a social relationship with that trafficker for years after his conviction, lied publicly about when the relationship ended, and was confirmed to a position with authority over sensitive technology exports and economic intelligence. The island visit is not peripheral — Little St. James is the location where victims were trafficked, where hidden cameras recorded visitors, and where the most compromising activities in the Epstein operation took place. Anyone who visited that island after Epstein's conviction — knowing what Epstein was — made a choice that raises questions about judgment at minimum and complicity at maximum. That this person now controls the Bureau of Industry and Security, which governs what sensitive technologies can be exported and to whom, is a national security concern that no congressional committee has examined. The question is not just what Lutnick did on the island — it's whether any recording exists, who might possess it, and what leverage it provides over a man who now holds one of the most sensitive positions in the US government.",
            link:"A sitting Commerce Secretary visited Epstein's island with his family in 2012 — four years after the conviction. He told the public he cut ties 'decades ago.' His own emails prove that was a lie. He was confirmed to a Cabinet position with authority over technology exports and national security while these emails sat in DOJ files. The island had hidden cameras. The Commerce Secretary controls what sensitive technologies America exports and to whom. No one has asked whether recordings exist. No one has asked who might have them. No one has asked what leverage they provide over a man making decisions about American economic security."},

        {id:"branson",label:"Richard Branson",type:"suspicious",radius:15,
            agency:"VIRGIN GROUP",role:"Billionaire · Virgin Group Founder",status:"NAMED IN FILES",networth:"$3B",
            intelRole:"Sir Richard Charles Nicholas Branson is the founder of the Virgin Group and one of the most recognizable billionaires on Earth. The 2026 DOJ file release revealed a correspondence between Branson and Epstein that goes far beyond any claim of casual acquaintance. In a 2013 email, Branson invited Epstein to his own private Caribbean island — Necker Island — telling him 'As long as you bring your harem!' This single email is the most casually explicit acknowledgment by any named associate that they were aware of and amused by Epstein's access to young women. The word 'harem' — used in reference to a convicted sex offender's companions — is not a term of endearment. It is an explicit recognition that Epstein traveled with a group of women whose presence was understood by those in his circle to be sexual in nature. Branson used the term with the ease of someone long accustomed to Epstein's arrangement. In separate correspondence, Branson advised Epstein on his post-conviction public image rehabilitation strategy — specifically suggesting that Epstein convince Bill Gates to publicly vouch for him, telling Epstein to get Gates to 'tell the public that Epstein had been a brilliant adviser to him.' This advice reveals that Branson was not merely aware of Epstein's conviction — he was actively strategizing about how to overcome it. He was coaching a convicted sex offender on public relations using the world's most famous philanthropist as a reputational shield. The combination of the 'harem' invitation and the Gates rehabilitation advice establishes that Branson knew what Epstein was, maintained the relationship anyway, invited him to his private island with his entourage, and helped him plan his return to social respectability.",
            epsteinLink:"The documented correspondence between Branson and Epstein reveals a relationship of comfort, familiarity, and active collaboration in managing the consequences of Epstein's conviction. The 2013 'harem' email — sent five years after Epstein's sex offender conviction — is an invitation to bring exactly the kind of entourage that had led to Epstein's criminal case. Branson was inviting a convicted sex offender to bring a group of young women to his private island. In the same period, Branson advised Epstein on reputation management — telling him to leverage his relationship with Bill Gates. This is not the behavior of a man who was unaware of Epstein's activities. It is the behavior of someone who was fully briefed, comfortable with what he knew, and willing to help manage the fallout. Necker Island — Branson's private Caribbean property — sits in the British Virgin Islands, approximately 90 miles from Epstein's Little St. James in the US Virgin Islands. The two billionaires owned private Caribbean islands in the same island chain. The proximity and the invitation suggest that the exchange of hospitality between private islands was a feature of their relationship. Flight records and travel documentation in the released files indicate multiple points of contact between Branson's and Epstein's travel patterns in the Caribbean.",
            desc:"Sir Richard Charles Nicholas Branson (b. 1950) is a British billionaire, founder of Virgin Group, and one of the world's most prominent entrepreneurs. His business empire spans airlines (Virgin Atlantic), telecommunications (Virgin Media), space tourism (Virgin Galactic), healthcare, financial services, and hospitality. He owns Necker Island, a 74-acre private island in the British Virgin Islands — approximately 90 miles from Epstein's Little St. James. Branson has cultivated a public image as a charismatic, socially conscious billionaire — a reputation that the released Epstein correspondence significantly undermines. The 'harem' email demonstrates a casual familiarity with Epstein's lifestyle that is incompatible with ignorance of his crimes. The Gates rehabilitation advice demonstrates active complicity in helping a convicted sex offender return to social prominence. Branson's public statements after Epstein's 2019 arrest were carefully managed. He acknowledged meeting Epstein but characterized the encounters as limited. The released correspondence proves the relationship was ongoing, warm, strategically collaborative, and included explicit references to the very behavior that led to Epstein's conviction. Branson has not been questioned under oath about the correspondence. No law enforcement agency has investigated the nature of any visits between the two men's private islands. The question of whether Epstein visited Necker Island — and who else was present if he did — has never been answered.",
            evidence:"2013 email from Branson to Epstein: 'Any time you're in the area would love to see you. As long as you bring your harem!' — sent five years after Epstein's sex offender conviction. Separate 2013 email advising Epstein to get Bill Gates to publicly vouch for him: telling Epstein to get Gates to 'tell the public that Epstein had been a brilliant adviser to him.' Both emails documented in the 2026 DOJ release. Necker Island is located approximately 90 miles from Little St. James in the same Caribbean island chain. Branson acknowledged meeting Epstein but characterized contacts as limited — the released correspondence contradicts this characterization. No law enforcement investigation has examined whether Epstein visited Necker Island or whether Branson visited Little St. James. Flight records in released files show travel pattern overlap in the Caribbean. Branson has not been questioned under oath about the correspondence. The 'harem' reference is the single most explicit casual acknowledgment by any named associate of Epstein's pattern of traveling with young women.",
            significance:"Richard Branson is not accused of participating in Epstein's abuse. What the correspondence establishes is something arguably more important for understanding how the Epstein network functioned — it shows how the social circle around Epstein normalized, facilitated, and actively assisted in maintaining the operation. Branson knew Epstein was a convicted sex offender. He invited him to his private island anyway. He told him to bring his 'harem.' He coached him on rehabilitating his reputation using Bill Gates. This is the behavior of a social ecosystem that protected Epstein not through ignorance but through active. The 'harem' email establishes that within Epstein's social circle, his access to young women was not hidden — it was a known feature of his lifestyle, referenced with casual humor by a fellow billionaire. The rehabilitation advice establishes that the social circle did not merely tolerate Epstein's conviction — it worked to overcome it. Every person who helped Epstein rehabilitate his public image after 2008 extended the period during which he was able to continue trafficking. Branson's advice to use Gates as a reputational shield was part of the machinery that kept the operation running for another decade.",
            link:"'As long as you bring your harem.' A billionaire invited a convicted sex offender to his private island and told him to bring the girls. Then he helped him plan his comeback using Bill Gates as a PR shield. The 'harem' email is the single most revealing piece of correspondence in the entire file release — not because it proves a crime, but because it proves that everyone in Epstein's circle knew exactly what he was and treated it as entertainment. The casual humor is the horror. When a billionaire jokes about a convicted sex trafficker's 'harem,' the word 'complicity' doesn't require a criminal charge to apply."},
        {id:"acosta",label:"Alexander Acosta",type:"suspicious",radius:23,
            most_suspicious: true,
            agency:"US DEPARTMENT OF JUSTICE / LABOR",role:"Former US Attorney · Former Labor Secretary",status:"RESIGNED",networth:"$5M",
            intelRole:"Alexander Acosta is the single most important witness to the fact that Jeffrey Epstein was an intelligence asset — because he said it out loud. As US Attorney for the Southern District of Florida, Acosta signed the 2008 non-prosecution agreement (NPA) that gave Epstein the most lenient sentence in federal sex trafficking history: 13 months in a county stockade with 12 hours of daily work release, during which Epstein continued to meet with young women at his Palm Beach office. The NPA also granted blanket immunity to all unnamed co-conspirators — meaning every client, every recruiter, every facilitator in the entire network was shielded from prosecution by a single document that Acosta signed. When Acosta was vetted for the position of Secretary of Labor during the Trump transition in 2017, he was asked about the Epstein deal. According to investigative journalist Vicky Ward, Acosta told the transition team: 'I was told Epstein belonged to intelligence and to leave it alone.' The statement was reported and never denied by Acosta. He was confirmed as Labor Secretary anyway — meaning the Trump administration was informed that a sex trafficker was an intelligence asset and responded by giving the prosecutor who protected him a Cabinet position. Acosta resigned in July 2019 after Epstein's re-arrest made his role in the 2008 deal untenable. He has never been questioned under oath about the 'belonged to intelligence' statement. No congressional inquiry has ever asked him which agency, which official, and through which channel the instruction to 'leave it alone' was transmitted. The answer to that question would identify which intelligence service ran Epstein — and every institution with the power to ask it has chosen not to.",
            epsteinLink:"Acosta signed the 2008 non-prosecution agreement as US Attorney for the Southern District of Florida. The NPA was negotiated directly with Epstein's defense team — which included Alan Dershowitz, Ken Starr, Jay Lefkowitz, and Gerald Lefcourt — a legal army that no ordinary sex offender could afford and that no ordinary case would attract. The deal gave Epstein 13 months in the Palm Beach County Stockade — not federal prison — with 12 hours of daily work release six days a week. During work release, Epstein was chauffeured to his Palm Beach office where, according to later reporting, he continued to meet with young women. The NPA also contained a provision unprecedented in federal law: blanket immunity for all unnamed co-conspirators. This single clause protected every person in Epstein's network — every client who received a trafficked minor, every recruiter who brought girls in, every assistant who scheduled the appointments, every pilot who flew the plane. The immunity was not limited to named individuals — it covered anyone who might have participated, whether named or not. This provision was so extraordinary that legal scholars have been unable to identify a precedent. The deal was negotiated in secret, without notifying the victims as required by the Crime Victims' Rights Act — a violation later confirmed by federal judge Kenneth Marra in 2019. Acosta approved every element. When later asked why, he said he was told Epstein 'belonged to intelligence.' The statement has never been investigated.",
            desc:"Alexander Acosta (b. 1969) served as US Attorney for the Southern District of Florida from 2005 to 2009. In that capacity, he oversaw the Epstein investigation that began with a Palm Beach Police Department referral in 2006. The Palm Beach PD investigation, led by Detective Joseph Recarey, had built a case involving over 40 identified underage victims — a case that should have resulted in federal sex trafficking charges carrying mandatory minimum sentences of 15 years to life. Instead, Acosta's office negotiated the NPA that gave Epstein 13 months with work release and blanket immunity for all co-conspirators. The deal was signed in September 2007 and kept secret from the victims until after it was finalized — a violation of the Crime Victims' Rights Act that federal judge Kenneth Marra ruled unlawful in February 2019. Detective Recarey, who built the case, later stated he was 'icheckfurious' at the deal and believed federal prosecutors had been pressured. He died in May 2018 at age 50 — officially of natural causes — shortly before the Miami Herald's Julie K. Brown published the investigation that led to Epstein's re-arrest. Acosta went on to become dean of Florida International University's law school before being nominated as Secretary of Labor by President Trump in 2017. During his confirmation process, the 'belonged to intelligence' statement was apparently not treated as disqualifying. He was confirmed by the Senate 60-40. He served as Labor Secretary — the Cabinet position responsible for labor trafficking enforcement — until his resignation on July 19, 2019, twelve days after Epstein's arrest on federal sex trafficking charges by the Southern District of New York. At his resignation press conference, Acosta defended the 2008 deal as 'the best that could be done' — a claim contradicted by Palm Beach PD, by the victims, by Judge Marra, and by the SDNY's subsequent ability to bring federal charges based on the same conduct.",
            evidence:"Signed the 2008 NPA giving Epstein 13 months with work release — documented in federal court records. NPA included blanket immunity for all unnamed co-conspirators — unprecedented provision documented in the agreement itself. Deal negotiated in secret without victim notification — ruled unlawful by Judge Kenneth Marra, February 2019. 'Belonged to intelligence' statement reported by Vicky Ward — Acosta has never denied it. Confirmed as Labor Secretary by Senate 60-40 in April 2017 despite the Epstein deal being public record. Resigned July 19, 2019, twelve days after Epstein's re-arrest. Detective Joseph Recarey built the original case identifying 40+ victims — died May 2018 at age 50 before the Miami Herald investigation published. Palm Beach PD case files documented over 40 identified underage victims. Epstein's defense team included Dershowitz, Starr, Lefkowitz, and Lefcourt. Acosta has never been questioned under oath about the 'belonged to intelligence' statement. No congressional inquiry has asked which agency or official conveyed the instruction. The Crime Victims' Rights Act violation was confirmed by a federal judge but resulted in no consequences for Acosta or any DOJ official.",
            significance:"Alexander Acosta is the Rosetta Stone of the Epstein case. His 'belonged to intelligence' statement is the single most important piece of testimony in the entire affair — a federal prosecutor confirming on the record that he was told a sex trafficker was an intelligence asset and was instructed to stand down. The NPA he signed did not merely protect Epstein — it protected every person in the network through blanket immunity for unnamed co-conspirators. This means the 2008 deal was not a plea bargain — it was an institutional decision to shield an entire intelligence-connected trafficking operation from prosecution. The fact that Acosta was subsequently rewarded with a Cabinet position — by the same president under whose administration Epstein would later die in custody — has never been examined. No congressional committee has ever subpoenaed Acosta to testify about which intelligence agency claimed Epstein, which official conveyed the message, and through which channel the instruction was transmitted. The answer to those questions would identify who ran the operation. Every institution that could ask has chosen silence.",
            link:"A federal prosecutor was told a sex trafficker 'belonged to intelligence' and was instructed to leave it alone. He signed a deal that gave the trafficker 13 months with work release and blanket immunity for every unnamed person in the network. He was then given a Cabinet position by the next president. He has never been questioned under oath about which intelligence agency claimed Epstein. No one has ever asked. That single question — 'Which agency?' — would crack the entire case open. The fact that no one in power has asked it in over 17 years tells you everything about who is being protected and why."},
//
        {id:"kellen",label:"Sarah Kellen",type:"suspicious",radius:31,
            most_suspicious: true,
            agency:"EPSTEIN INNER CIRCLE",role:"Executive Assistant · Named Co-Conspirator",status:"GRANTED IMMUNITY (2008 NPA)",
            birthday_book: true,
            intelRole:"Sarah Kellen managed Epstein's daily schedule for approximately a decade. The FBI named her as a potential co-conspirator during its investigation. She received blanket immunity under the 2008 non-prosecution agreement. Multiple victims identified her in sworn depositions as the person who contacted them by phone, arranged their visits, and directed them within Epstein's properties.",
            epsteinLink:"Victims testified under oath that Kellen was the person who called them, arranged transportation, and directed them to specific rooms at Epstein's properties. She maintained Epstein's appointment calendar and coordinated the logistics of visits. The 2008 NPA negotiated by Epstein's defense team included blanket immunity for unnamed co-conspirators — Kellen among them. This immunity removed any prosecutorial leverage that could have compelled her testimony about others involved in the operation. She has never been deposed in any civil proceeding, never testified publicly, and has not spoken to media about her role.",
            desc:"Sarah Kellen (now Sarah Kellen Vickers) served as Jeffrey Epstein's executive assistant. The FBI's investigation identified her as a potential co-conspirator. Multiple victims named her in sworn statements as the person who scheduled their visits and directed them within properties. She received immunity under the 2008 NPA. She later married NASCAR driver Brian Vickers. She has made no public statements regarding the Epstein case.",
            evidence:"Identified as potential co-conspirator in FBI investigation — federal case files. Granted immunity under 2008 NPA. Multiple victims identified her by name in sworn depositions as scheduling visits and directing them within properties. Maintained Epstein's operational calendar. Listed in Epstein's black book. Never deposed in civil proceedings. No public statements regarding the case.",
            significance:"Kellen's role as scheduler means she possessed direct knowledge of who visited Epstein's properties and when. The immunity provision removed the primary legal mechanism — threat of prosecution — that could compel her cooperation. The person with the most complete operational knowledge of Epstein's daily appointments has never been required to share that knowledge with investigators or the public.",
            link:"She scheduled the appointments. She directed the visits. The FBI called her a co-conspirator. The immunity deal ensured she would never have to testify about what she knew. The most operationally informed person in the Epstein case has never spoken a word about it publicly."},

        {id:"marcinkova",label:"Nadia Marcinkova",type:"suspicious",radius:17,
            most_suspicious: true,
            agency:"EPSTEIN INNER CIRCLE",role:"Trafficked Victim Turned Participant",status:"GRANTED IMMUNITY (2008 NPA)",
            birthday_book: true,
            intelRole:"Brought from Eastern Europe by Epstein as a teenager. Victims say she was made to participate in abuse.",
            epsteinLink:"Epstein allegedly purchased her from her family in Eastern Europe. Multiple victims say she participated in their abuse at Epstein's direction.",
            desc:"Nadia Marcinkova was brought from Eastern Europe by Epstein as a teenager — victims allege he 'purchased' her from her family. She was both a victim and, according to other victims' testimony, made into a participant in abuse. She received immunity in the 2008 deal and later became a pilot, rebranding as Nadia Marcinko.",
            evidence:"Named co-conspirator in federal filings. Granted immunity under 2008 NPA. Multiple victims described her participating in abuse. Rebranded as Global Girl Aviation founder.",
            significance:"The most tragic figure in the case — trafficked as a child, made into a participant, then immunized into silence.",
            link:"Trafficked from Eastern Europe as a child, made to participate, granted immunity, silenced forever."},

        {id:"groff",label:"Lesley Groff",type:"suspicious",radius:17,
            most_suspicious: true,
            agency:"EPSTEIN INNER CIRCLE",role:"Executive Assistant · Named Co-Conspirator",status:"GRANTED IMMUNITY (2008 NPA)",
            birthday_book: true,
            intelRole:"Managed Epstein's travel, property logistics, and bookings for decades.",
            epsteinLink:"Booked every flight, managed every property. Named co-conspirator who received immunity.",
            desc:"Lesley Groff was Epstein's longtime executive assistant who managed travel arrangements, property logistics, and scheduling. She was named as a co-conspirator but received immunity under the 2008 NPA.",
            evidence:"Named co-conspirator in federal filings. Granted immunity under 2008 NPA. Travel and scheduling records show her involvement spanning decades.",
            significance:"She booked every flight and managed every property. Her records would map the entire operation.",
            link:"The logistics coordinator who booked every flight and managed every property — immunized into silence."},

        {id:"eva_dubin",label:"Eva Andersson-Dubin",type:"suspicious",radius:12,
            agency:"PHYSICIAN",role:"Physician · Former Miss Sweden · Epstein's Ex-Girlfriend",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"Epstein's former girlfriend who married hedge fund billionaire Glenn Dubin. Maintained contact with Epstein for decades after.",
            epsteinLink:"Dated Epstein in the 1980s. After marrying Dubin, the couple maintained a close relationship with Epstein — including allowing their teenage daughter to spend time with him unsupervised.",
            desc:"Eva Andersson-Dubin, former Miss Sweden and physician, dated Epstein in the 1980s before marrying Glenn Dubin. The couple maintained a close relationship with Epstein after — reportedly allowing their underage daughter to be in Epstein's company.",
            evidence:"Signed Epstein's birthday book. Relationship with Epstein documented. Dubin named by Giuffre. Reports of their daughter spending unsupervised time with Epstein.",
            significance:"An ex-girlfriend who maintained the relationship and allegedly allowed her own child access to a known predator.",
            link:"The Dubins' continued closeness to Epstein — including reportedly allowing access to their daughter — is among the most disturbing patterns in the case."},

        {id:"briatore",label:"Flavio Briatore",type:"suspicious",radius:9,
            agency:"FORMULA ONE / BILLIONAIRE'S CLUB",role:"F1 Team Boss · Businessman",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"Formula One team principal. Part of Epstein's jet-set social circle.",
            epsteinLink:"Signed Epstein's birthday book. Named in contact files. Part of the same European jet-set circle as Brunel and Naomi Campbell.",
            desc:"Flavio Briatore was a Formula One team principal and businessman. He signed Epstein's birthday book and was part of the overlapping European social circle that included Brunel, Naomi Campbell, and Maxwell.",
            evidence:"Signed Epstein's birthday book. Named in contact files. Dated Naomi Campbell. Convicted of fraud in Italy (later overturned).",
            link:"Part of the European jet-set circle where modeling, wealth, and Epstein's network converged."},

        {id:"ari_emanuel",label:"Ari Emanuel",type:"suspicious",radius:10,
            agency:"WME / ENDEAVOR",role:"Hollywood Super-Agent · Endeavor CEO",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"Hollywood's most powerful talent agent. Brother of Rahm Emanuel (Obama Chief of Staff, Chicago Mayor).",
            epsteinLink:"Signed Epstein's birthday book. Named in contact files.",
            desc:"Ari Emanuel is the CEO of Endeavor (parent of WME talent agency and UFC). He is Hollywood's most powerful talent agent and brother of Rahm Emanuel. He signed Epstein's birthday book.",
            evidence:"Signed Epstein's birthday book. Named in Epstein's contact files. Controls access to Hollywood talent.",
            significance:"The most powerful gatekeeper in Hollywood signed a sex trafficker's birthday book.",
            link:"Hollywood's top gatekeeper in Epstein's birthday book."},

        {id:"kravis",label:"Henry Kravis",type:"suspicious",radius:11,
            agency:"KKR & CO",role:"Private Equity Billionaire",status:"NAMED IN FILES",networth:"$10B",
            birthday_book: true,
            intelRole:"Co-founder of KKR, one of the largest private equity firms in the world.",
            epsteinLink:"Signed Epstein's birthday book. Named in contact files. Part of the same New York billionaire social circle.",
            desc:"Henry Kravis co-founded KKR & Co, one of the world's largest private equity firms. He signed Epstein's birthday book and appears in Epstein's contact files.",
            evidence:"Signed Epstein's birthday book. Named in Epstein's contact files.",
            significance:"Another billionaire in Epstein's birthday book and contact list.",
            link:"The co-founder of one of the world's largest private equity firms signed a sex trafficker's birthday book."},

        {id:"stroll",label:"Lawrence Stroll",type:"suspicious",radius:8,
            agency:"ASTON MARTIN / RACING POINT",role:"F1 Team Owner · Fashion Billionaire",status:"NAMED IN FILES",networth:"$3.6B",
            birthday_book: true,
            intelRole:"Fashion and automotive billionaire. Part of the same circles as Briatore.",
            epsteinLink:"Signed Epstein's birthday book. Named in contact files.",
            desc:"Lawrence Stroll is a Canadian billionaire, owner of Aston Martin F1 team, and fashion investor (Tommy Hilfiger, Michael Kors, Ralph Lauren). He signed Epstein's birthday book.",
            evidence:"Signed Epstein's birthday book. Named in Epstein's contact files.",
            significance:"Another billionaire who signed the birthday book.",
            link:"Fashion billionaire and F1 team owner in Epstein's birthday book."},

        {id:"blanchett",label:"Cate Blanchett",type:"suspicious",radius:8,
            agency:"ACTRESS",role:"Actress",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"Oscar-winning actress.",
            epsteinLink:"Signed Epstein's birthday book.",
            desc:"Cate Blanchett, the Oscar-winning actress, signed Epstein's birthday book.",
            evidence:"Signed Epstein's birthday book.",
            significance:"An Oscar winner in Epstein's birthday book.",
            link:"Signed Epstein's birthday book."},

        {id:"christy_turlington",label:"Christy Turlington",type:"suspicious",radius:8,
            agency:"MODEL",role:"Supermodel",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"Supermodel connected to the same fashion industry pipeline as Brunel and Campbell.",
            epsteinLink:"Signed Epstein's birthday book.",
            desc:"Christy Turlington, one of the original supermodels, signed Epstein's birthday book.",
            evidence:"Signed Epstein's birthday book.",
            significance:"Another supermodel in Epstein's orbit — the fashion-trafficking pipeline connection.",
            link:"Signed Epstein's birthday book."},

        {id:"david_koch",label:"David Koch",type:"suspicious",radius:11,
            agency:"KOCH INDUSTRIES",role:"Billionaire Industrialist",status:"DECEASED (2019)",networth:"$50B (at death)",
            birthday_book: true,
            intelRole:"One of the Koch brothers. Massive Republican donor and political influencer.",
            epsteinLink:"Signed Epstein's birthday book. Named in contact files.",
            desc:"David Koch, billionaire industrialist and Republican mega-donor, signed Epstein's birthday book. He died in August 2019 — the same month as Epstein.",
            evidence:"Signed Epstein's birthday book. Named in Epstein's contact files.",
            significance:"One of the most politically influential billionaires in America signed a sex trafficker's birthday book.",
            link:"A Koch brother signed Epstein's birthday book."},

        {id:"itzhak_perlman",label:"Itzhak Perlman",type:"suspicious",radius:7,
            agency:"MUSICIAN",role:"Violinist",status:"NAMED IN FILES",
            birthday_book: true,
            intelRole:"World-renowned violinist.",
            epsteinLink:"Signed Epstein's birthday book.",
            desc:"Itzhak Perlman, the world-renowned violinist, signed Epstein's birthday book.",
            evidence:"Signed Epstein's birthday book.",
            significance:"Cultural figures used to legitimize Epstein's social world.",
            link:"Signed Epstein's birthday book."},
    ],

    links: [
        // Epstein center connections
        {source:"epstein", target:"maxwell_g", strength:1.0},
        {source:"epstein", target:"brunel", strength:0.8},
        {source:"epstein", target:"nader", strength:0.4},
        {source:"epstein", target:"trump", strength:0.7},
        {source:"epstein", target:"clinton", strength:0.8},
        {source:"epstein", target:"andrew", strength:0.7},
        {source:"epstein", target:"musk", strength:0.6},
        {source:"epstein", target:"gates", strength:0.7},
        {source:"epstein", target:"wexner", strength:0.9},
        {source:"epstein", target:"staley", strength:0.8},
        {source:"epstein", target:"dubin", strength:0.6},
        {source:"epstein", target:"mitchell", strength:0.5},
        {source:"epstein", target:"sultan_brunei", strength:0.4},
        {source:"epstein", target:"dershowitz", strength:0.8},
        {source:"epstein", target:"black", strength:0.7},
        {source:"epstein", target:"joi_ito", strength:0.6},
        {source:"epstein", target:"summers", strength:0.5},
        {source:"epstein", target:"hoffman", strength:0.5},
        {source:"epstein", target:"krauss", strength:0.5},
        {source:"epstein", target:"copperfield", strength:0.5},
        {source:"epstein", target:"dimon", strength:0.5},
        {source:"epstein", target:"blair", strength:0.4},
        {source:"epstein", target:"mort_z", strength:0.4},
        {source:"epstein", target:"pritzker", strength:0.5},
        {source:"epstein", target:"burkle", strength:0.4},
        {source:"epstein", target:"lutnick", strength:0.6},
        {source:"epstein", target:"branson", strength:0.6},
        {source:"epstein", target:"tisch", strength:0.6},
        {source:"epstein", target:"wasserman", strength:0.4},
        {source:"epstein", target:"barak", strength:0.7},
        {source:"epstein", target:"thiel", strength:0.6},
        {source:"epstein", target:"mandelson", strength:0.7},
        {source:"epstein", target:"barrack", strength:0.5},
        {source:"epstein", target:"casablancas", strength:0.5},
        {source:"epstein", target:"woody", strength:0.4},
        {source:"epstein", target:"spacey", strength:0.4},
        {source:"epstein", target:"tucker", strength:0.3},
        {source:"epstein", target:"richardson", strength:0.5},
        {source:"epstein", target:"sultan_ahmed", strength:0.3},
        {source:"epstein", target:"naomi", strength:0.3},
        {source:"epstein", target:"minsky", strength:0.4},
        {source:"epstein", target:"pinker", strength:0.3},
        {source:"epstein", target:"chomsky", strength:0.3},
        {source:"epstein", target:"deepak", strength:0.3},
        {source:"epstein", target:"nicholas_neg", strength:0.4},
        {source:"epstein", target:"lajcak", strength:0.3},
        {source:"epstein", target:"ferguson", strength:0.4},
        {source:"epstein", target:"brin", strength:0.4},
        {source:"epstein", target:"bannon", strength:0.5},
        {source:"epstein", target:"zuckerberg", strength:0.4},
        {source:"epstein", target:"mette_marit", strength:0.5},

        // Maxwell connections
        {source:"maxwell_g", target:"andrew", strength:0.7},
        {source:"maxwell_g", target:"brunel", strength:0.7},
        {source:"maxwell_g", target:"naomi", strength:0.5},
        {source:"maxwell_g", target:"woody", strength:0.4},
        {source:"maxwell_g", target:"wasserman", strength:0.4},
        {source:"maxwell_g", target:"brin", strength:0.4},
        {source:"maxwell_g", target:"casablancas", strength:0.5},
        {source:"maxwell_g", target:"minsky", strength:0.4},
        {source:"maxwell_g", target:"ferguson", strength:0.4},

        // Cross-connections
        {source:"clinton", target:"spacey", strength:0.4},
        {source:"clinton", target:"tucker", strength:0.4},
        {source:"clinton", target:"burkle", strength:0.5},
        {source:"wexner", target:"barak", strength:0.5},
        {source:"dershowitz", target:"pinker", strength:0.3},
        {source:"hoffman", target:"joi_ito", strength:0.5},
        {source:"hoffman", target:"zuckerberg", strength:0.4},
        {source:"hoffman", target:"musk", strength:0.3},
        {source:"joi_ito", target:"nicholas_neg", strength:0.5},
        {source:"joi_ito", target:"summers", strength:0.3},
        {source:"barak", target:"thiel", strength:0.5},
        {source:"barak", target:"barrack", strength:0.4},
        {source:"thiel", target:"zuckerberg", strength:0.3},
        {source:"thiel", target:"musk", strength:0.3},
        {source:"mandelson", target:"blair", strength:0.6},
        {source:"andrew", target:"ferguson", strength:0.5},
        {source:"brunel", target:"casablancas", strength:0.6},
        {source:"gates", target:"branson", strength:0.4},
        {source:"staley", target:"dimon", strength:0.5},
        {source:"trump", target:"lutnick", strength:0.4},
        {source:"trump", target:"bannon", strength:0.5},
        {source:"trump", target:"barrack", strength:0.5},
        {source:"trump", target:"nader", strength:0.3},
        {source:"musk", target:"brin", strength:0.3},

        // ─── INTELLIGENCE LINKS ───
        {source:"epstein", target:"robert_maxwell", strength:0.7},
        {source:"maxwell_g", target:"robert_maxwell", strength:1.0},
        {source:"epstein", target:"acosta", strength:0.7},
        {source:"epstein", target:"ben_menashe", strength:0.3},
        {source:"epstein", target:"barr_w", strength:0.5},
        {source:"epstein", target:"barr_d", strength:0.4},
        {source:"epstein", target:"hoffenberg", strength:0.6},
        {source:"epstein", target:"khashoggi", strength:0.4},
        {source:"epstein", target:"dougan", strength:0.2},
        {source:"barr_w", target:"barr_d", strength:0.9},
        {source:"barr_w", target:"trump", strength:0.5},
        {source:"barr_w", target:"acosta", strength:0.5},
        {source:"robert_maxwell", target:"ben_menashe", strength:0.6},
        {source:"robert_maxwell", target:"khashoggi", strength:0.5},
        {source:"acosta", target:"dershowitz", strength:0.5},

        // ─── POSSIBLY INVOLVED LINKS ───
        {source:"epstein", target:"putin", strength:0.3},
        {source:"putin", target:"robert_maxwell", strength:0.6},
        {source:"putin", target:"mbs", strength:0.4},
        {source:"epstein", target:"king_charles", strength:0.4},
        {source:"king_charles", target:"andrew", strength:1.0},
        {source:"king_charles", target:"ferguson", strength:0.7},
        {source:"epstein", target:"mbs", strength:0.3},
        {source:"mbs", target:"khashoggi", strength:0.7},
        {source:"mbs", target:"nader", strength:0.6},
        {source:"mbs", target:"sultan_brunei", strength:0.5},
        {source:"mbs", target:"trump", strength:0.6},
        {source:"epstein", target:"kissinger", strength:0.5},
        {source:"kissinger", target:"robert_maxwell", strength:0.4},
        {source:"kissinger", target:"khashoggi", strength:0.5},
        {source:"epstein", target:"brennan", strength:0.3},
        {source:"murdoch", target:"robert_maxwell", strength:0.7},
        {source:"murdoch", target:"trump", strength:0.6},
        {source:"murdoch", target:"blair", strength:0.5},
        {source:"murdoch", target:"king_charles", strength:0.4},
        {source:"epstein", target:"petraeus", strength:0.3},
        {source:"starr", target:"dershowitz", strength:0.8},
        {source:"starr", target:"acosta", strength:0.6},
        {source:"starr", target:"clinton", strength:0.5},
        {source:"epstein", target:"boies", strength:0.6},
        {source:"boies", target:"dershowitz", strength:0.5},
        {source:"boies", target:"maxwell_g", strength:0.4},
        {source:"epstein", target:"ellison", strength:0.4},
        {source:"ellison", target:"gates", strength:0.4},
        {source:"ellison", target:"brin", strength:0.3},
        {source:"ellison", target:"thiel", strength:0.4},
        {source:"epstein", target:"netanyahu", strength:0.3},
        {source:"netanyahu", target:"barak", strength:0.7},
        {source:"netanyahu", target:"murdoch", strength:0.5},
        {source:"netanyahu", target:"kissinger", strength:0.4},
        {source:"netanyahu", target:"trump", strength:0.6},
        {source:"netanyahu", target:"robert_maxwell", strength:0.5},
        {source:"netanyahu", target:"wexner", strength:0.4},

        // ─── BIRTHDAY BOOK / INNER CIRCLE LINKS ───
        {source:"epstein", target:"kellen", strength:0.9},
        {source:"epstein", target:"marcinkova", strength:0.8},
        {source:"epstein", target:"groff", strength:0.8},
        {source:"epstein", target:"eva_dubin", strength:0.5},
        {source:"epstein", target:"briatore", strength:0.4},
        {source:"epstein", target:"ari_emanuel", strength:0.4},
        {source:"epstein", target:"kravis", strength:0.4},
        {source:"epstein", target:"stroll", strength:0.3},
        {source:"epstein", target:"david_koch", strength:0.4},
        {source:"epstein", target:"clinton", strength:0.4},
        {source:"maxwell_g", target:"kellen", strength:0.7},
        {source:"maxwell_g", target:"marcinkova", strength:0.6},
        {source:"maxwell_g", target:"groff", strength:0.6},
        {source:"eva_dubin", target:"dubin", strength:0.9},
        {source:"kellen", target:"marcinkova", strength:0.5},
        {source:"kellen", target:"groff", strength:0.5},
        {source:"briatore", target:"naomi", strength:0.5},
        {source:"briatore", target:"stroll", strength:0.4},
        {source:"christy_turlington", target:"naomi", strength:0.4},
        {source:"brunel", target:"christy_turlington", strength:0.3},
    ]
};